class Protocol:
	NAME = None
	RULE_ID_SIZE = 0
	L2_WORD_SIZE = 0
	TILE_SIZE = 0
	M = 0
	N = 0
	M = 0
	BITMAP_SIZE = 0
	RCS_SIZE = 0
	RCS_ALGORITHM = None
	T = 0
	MAX_ACK_REQUESTS = 0
	MAX_WIND_FCN = 0
	RETRANSMISSION_TIMER_VALUE = None
	INACTIVITY_TIMER_VALUE = None
	MTU = 0
